version: "3.9"

services:
  api-service-0:
    container_name: api-container-0
    build:
      context: ./
      dockerfile: Dockerfile
    #    image: api-image-sample
    environment:
      API_TITLE: API docs dev
    ports:
      - '8080:8080'
    networks:
      - backend

  api-service-1:
    container_name: api-container-1
    build:
      context: ./
      dockerfile: Dockerfile
#    image: api-image-sample
    environment:
      API_TITLE: API docs test
    ports:
      - '8081:8080'
    networks:
      - backend

  api-service-2:
    container_name: api-container-2
    build:
      context: ./
      dockerfile: Dockerfile
#    image: api-image-sample
    environment:
      API_TITLE: API docs prod
    ports:
      - '8082:8080'
    networks:
      - backend

networks:
  backend:
    driver: bridge