version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=Vl121620.
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - backend

  api-service-0:
    container_name: api-container-0
    build:
      context: ./
      dockerfile: Dockerfile
    #    image: api-image-sample
    environment:
      API_TITLE: API docs dev
    ports:
      - '8080:8080'
    networks:
      - backend

  api-service-1:
    container_name: api-container-1
    build:
      context: ./
      dockerfile: Dockerfile
#    image: api-image-sample
    environment:
      API_TITLE: API docs test
    ports:
      - '8081:8080'
    networks:
      - backend

  api-service-2:
    container_name: api-container-2
    build:
      context: ./
      dockerfile: Dockerfile
#    image: api-image-sample
    environment:
      API_TITLE: API docs prod
    ports:
      - '8082:8080'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql_data: