version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=Vl121620.
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - backend

  redis:
    image: redis:6.2-alpine
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB;FLUSHALL
    networks:
      - backend

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '22181:2181'

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - '29092:29092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1



  api-service-0:
    container_name: backend-service
    build:
      context: ./
      dockerfile: Dockerfile
    #    image: api-image-sample
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - API_TITLE=API docs dev
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Vl121620.
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_HOST=kafka
      - KAFKA_PORT=29092
      - CLOUDINARY_NAME=dthlb2txt
      - CLOUDINARY_API_KEY=457682188489763
      - CLOUDINARY_SECRET_KEY=tmwawye9jutKIZX63MIuaKfy6Hc
      - JWT_ACCESS_KEY=9ArFXUmmRUZlWtvhVr3I7ryL48QsE0AakGRdc3qfGhWGVy23hdBY8Ro9d/S1sVCe5KQHyFAx+YtP9PCGwv4Nsg==
      - JWT_REFRESH_KEY=MvsbX1u73zwkYUAgKBlCh7XR31fpkpmHdpMfVEk7Y0UKpcc3j0YIGS2z7JSd2OLiYYmWVjiYbHp+c3d2qdhv1A==
      - ZALOPAY_APP_ID=2554
      - ZALOPAY_KEY1=sdngKKJmqEMzvh5QQcdD2A9XBSKUNaYn
      - ZALOPAY_KEY2=trMrHtvjo6myautxDUiAcYsVtaeQ8nhf
    ports:
      - '8080:8080'
    depends_on:
      - mysql
      - redis
      - kafka
    networks:
      - backend

  api-service-1:
    container_name: api-container-1
    build:
      context: ./
      dockerfile: Dockerfile
#    image: api-image-sample
    environment:
      API_TITLE: API docs test
    ports:
      - '8081:8080'
    networks:
      - backend

  api-service-2:
    container_name: api-container-2
    build:
      context: ./
      dockerfile: Dockerfile
#    image: api-image-sample
    environment:
      API_TITLE: API docs prod
    ports:
      - '8082:8080'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql_data: